name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  contract:
    name: Contract build & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo_home-${{ hashFiles('**/Cargo.lock') }}-v8
    - name: Cache target
      uses: actions/cache@v4
      with:
        path: |
          contract/target/
        key: ${{ runner.os }}-contract_target-${{ hashFiles('**/Cargo.lock') }}-v8
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.57.0
        targets: wasm32-unknown-unknown
        components: rustfmt, clippy
    - name: Cargo build
      working-directory: contract
      run: RUSTFLAGS='-C link-arg=-s' cargo build --target wasm32-unknown-unknown --release
    - name: Copy wasm
      working-directory: contract
      run: rsync -t target/wasm32-unknown-unknown/release/marketplace.wasm res/marketplace.wasm
    - name: Cargo test
      working-directory: contract
      run: cargo test -- --nocapture

  frontend:
    name: Frontend build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: frontend/yarn.lock
    - name: Install dependencies
      working-directory: frontend
      run: yarn install --frozen-lockfile
    - name: Create dist directory
      working-directory: frontend
      run: mkdir -p dist && touch dist/lock_unlock_account_latest.wasm
    - name: Build
      working-directory: frontend
      run: npx parcel build src/index.html --public-url ./
